import { CourseAssetsType } from "@/types/assets";
import { EventType } from "@/types/event";
import { ReactNode } from "react";
import {
  Flag,
  GraduationCap,
  Bookmark,
  Calendar,
  MessageSquare,
  FileText,
  Users,
  Mic2,
  AlertCircle,
  Link,
  Video,
  ListMusic as Audio,
} from "lucide-react";

export const eventTypeClasses: Record<EventType | CourseAssetsType, string> = {
  exam: "bg-red-500/10 text-red-500",
  lecture: "bg-blue-500/10 text-blue-500",
  deadline: "bg-violet-500/10 text-violet-500",
  other: "bg-gray-500/10 text-gray-500",
  meeting: "bg-green-500/10 text-green-500",
  workshop: "bg-yellow-500/10 text-yellow-500",
  assignment: "bg-orange-500/10 text-orange-500",
  project: "bg-purple-500/10 text-purple-500",
  presentation: "bg-pink-500/10 text-pink-500",
  discussion: "bg-cyan-500/10 text-cyan-500",
  assets: "bg-amber-500/10 text-amber-500",
  announcement: "bg-indigo-500/10 text-indigo-500",
  slide: "bg-teal-500/10 text-teal-500",
  sheet: "bg-lime-500/10 text-lime-500",
  link: "bg-sky-500/10 text-sky-500",
  video: "bg-red-500/10 text-red-500",
  audio: "bg-blue-500/10 text-blue-500",
  resource: "bg-green-500/10 text-green-500",
  reading: "bg-yellow-500/10 text-yellow-500",
  quiz: "bg-pink-500/10 text-pink-500",
  test: "bg-red-500/10 text-red-500",
  lab: "bg-gray-500/10 text-gray-700",
  tutorial: "bg-blue-500/10 text-blue-800",
  file: "bg-gray-400/10 text-gray-500",
};

export const eventIcons: Record<EventType | CourseAssetsType, ReactNode> = {
  exam: <Flag className="h-4 w-4" />,
  lecture: <GraduationCap className="h-4 w-4" />,
  deadline: <Bookmark className="h-4 w-4" />,
  other: <Calendar className="h-4 w-4" />,
  meeting: <Users className="h-4 w-4" />,
  workshop: <Calendar className="h-4 w-4" />,
  assignment: <FileText className="h-4 w-4" />,
  project: <FileText className="h-4 w-4" />,
  presentation: <Mic2 className="h-4 w-4" />,
  discussion: <MessageSquare className="h-4 w-4" />,
  assets: <Bookmark className="h-4 w-4" />,
  announcement: <AlertCircle className="h-4 w-4" />,
  slide: <FileText className="h-4 w-4" />,
  sheet: <FileText className="h-4 w-4" />,
  link: <Link className="h-4 w-4" />,
  video: <Video className="h-4 w-4" />,
  audio: <Audio className="h-4 w-4" />,
  resource: <FileText className="h-4 w-4" />,
  reading: <FileText className="h-4 w-4" />,
  quiz: <FileText className="h-4 w-4" />,
  test: <FileText className="h-4 w-4" />,
  lab: <FileText className="h-4 w-4" />,
  tutorial: <FileText className="h-4 w-4" />,
  file: <FileText className="h-4 w-4" />,
};
